ACTIONS = [
    "running",
    "walking",
    "cooking",
    "cleaning",
    "driving a car",
    "using a laptop",
    "playing football",
    "playing basketball",
    "taking a photo",
    "talking on the phone",
    "reading",
    "writing",
    "lifting weights",
    "sleeping",
    "eating",
    "drinking",
    "shopping",
    "working at a desk",
    "playing video games",
    "swimming",
    "dancing",
]
