# TODO migrate to DB
SCENES = [
    # --- Indoor ---
    "kitchen",
    "bedroom",
    "living room",
    "dining room",
    "bathroom",
    "garage",
    "hallway",
    "laundry room",
    "closet",
    "basement",
    "attic",
    "office",
    "home office",
    "coworking space",
    "conference room",
    "computer lab",
    "classroom",
    "school hallway",
    "gym room",
    "fitness studio",
    "yoga studio",
    "library",
    "public library",
    "university classroom",
    "university hallway",
    "museum gallery",
    "art studio",
    "music studio",
    "recording booth",
    "theater stage",
    "cinema lobby",
    "shopping mall interior",
    "supermarket aisle",
    "warehouse interior",
    "factory interior",
    "workshop",
    "restaurant interior",
    "cafe interior",
    "coffee shop",
    "bar interior",
    "nightclub",
    "kitchen restaurant",
    "hotel lobby",
    "hotel room",
    "hospital room",
    "surgery room",
    "pharmacy interior",
    "laboratory interior",
    "waiting room",
    "elevator interior",
    "subway station interior",
    "airport terminal",
    "train station interior",
    "bus interior",
    "train interior",
    "airplane cabin",
    "church interior",
    "temple interior",
    "mosque interior",
    # --- Urban Outdoor ---
    "city street",
    "downtown",
    "suburban neighborhood",
    "alleyway",
    "parking lot",
    "rooftop",
    "bridge",
    "overpass",
    "construction site",
    "skyscraper area",
    "public square",
    "market street",
    "shopping district",
    "outdoor cafe",
    "sidewalk",
    "crosswalk",
    "bus stop",
    "train platform",
    "subway entrance",
    "harbor",
    "industrial area",
    "railway yard",
    "gas station",
    "car dealership",
    "skatepark",
    "basketball court outdoor",
    "tennis court outdoor",
    "stadium exterior",
    "amusement park",
    "zoo entrance",
    "theme park ride area",
    "playground",
    "school courtyard",
    "university campus",
    "cemetery",
    "churchyard",
    "park walkway",
    "urban garden",
    "botanical garden",
    # --- Nature Outdoor ---
    "forest",
    "mountain",
    "hill",
    "cliffside",
    "lake shore",
    "riverbank",
    "waterfall",
    "desert",
    "canyon",
    "beach",
    "tropical beach",
    "rocky beach",
    "ocean view",
    "meadow",
    "field",
    "farm",
    "vineyard",
    "orchard",
    "garden",
    "flower field",
    "snowy forest",
    "snowy mountain",
    "ice cave",
    "glacier",
    "savannah",
    "jungle",
    "rainforest",
    "volcano area",
    "hot spring area",
    "cave interior natural",
    "wetlands",
    "swamp",
    "marshland",
    "river crossing",
    "bridge over water",
    "sunset landscape",
    "sunrise landscape",
    "night sky scene",
    "starry sky",
    "aurora borealis",
    # --- Transport / Transit ---
    "highway",
    "country road",
    "tunnel",
    "roundabout",
    "airport runway",
    "helicopter pad",
    "pier",
    "dockyard",
    "ferry terminal",
    "border checkpoint",
    # --- Sports / Activity Scenes ---
    "football field",
    "basketball court indoor",
    "tennis court indoor",
    "swimming pool",
    "boxing gym",
    "martial arts dojo",
    "climbing gym",
    "running track",
    "ice rink",
    "ski slope",
    "golf course",
    "surfing beach",
    "skating rink",
    "track stadium",
    "cycling trail",
    # --- Events / Social Scenes ---
    "wedding ceremony",
    "wedding reception",
    "birthday party",
    "concert stage",
    "music festival",
    "conference event",
    "press room",
    "banquet hall",
    "night festival",
    "street parade",
    "dance club floor",
    "art exhibition",
    "book fair",
    # --- Work / Profession Scenes ---
    "construction workshop",
    "car repair shop",
    "hair salon",
    "barbershop",
    "optician store",
    "medical clinic",
    "fire station interior",
    "police station interior",
    "broadcast studio",
    "newsroom",
    "server room",
    "data center",
    "control room",
    "power plant interior",
    # --- Shops / Commerce ---
    "clothing store",
    "electronics store",
    "toy store",
    "bookstore",
    "hardware store",
    "jewelry store",
    "pet shop",
    "bakery interior",
    "butcher shop",
    "fish market",
    "farmer market",
    "wine store",
    # --- Food Scenes ---
    "kitchen cooking",
    "street food stand",
    "food truck",
    "restaurant terrace",
    "buffet table",
    "bar counter",
    # --- Special / Rare Scenes ---
    "abandoned building",
    "ruins",
    "underground bunker",
    "server closet",
    "observatory",
    "planetarium",
    "science fair",
    "robotics lab",
    "virtual reality room",
    "arcade room",
    "casino floor",
    "escape room",
    "medieval village",
    "castle courtyard",
    "farm barn interior",
    "windmill area",
    "lighthouse area",
]